# .github/workflows/ci.yml

# Quickstart CI workflow
# https://github.com/actions-rs/meta/blob/master/recipes/quickstart.md

# ###
# Action name
name: Continuous integration

on:
  pull_request:
  push:
    branches:
      - master

# A map of default settings that will apply to all jobs in the workflow.
defaults:
  run:
    shell: bash

# ###
# Workflow run and it's job components.
# Note: Jobs run in parallel by default.
jobs:
  # Check a local package and all of its dependencies for errors.
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: sudo apt-get install libssl-dev libudev-dev pkg-config zlib1g-dev llvm clang make
      - uses: actions-rs/cargo@v1
        with:
          command: check

  # Run Tests
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get install libssl-dev libudev-dev pkg-config zlib1g-dev llvm clang make
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test

  # Format Rust code
  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  # A collection of lints to catch common mistakes and improve your Rust code.
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: sudo apt-get install libssl-dev libudev-dev pkg-config zlib1g-dev llvm clang make
      - run: rustup component add clippy
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
